### ISSUE TITLE
How to use the admon plugin through the mdformat api?

### ISSUE THREAD

**Issue by veghdev** [KyleKing/mdformat-admon#11]
Other plugins can be used with the api (see the example below), but if I try to use mdformat-admon I get error:
plugin = mdformat.plugins.PARSER_EXTENSIONS[name]
KeyError: 'admon'

```py
import mdformat

mdformat.text(
        content,
        options={"wrap": 80, "end-of-line": "keep"},
        extensions={
            "gfm",
            "tables",
            "footnote",
            "frontmatter",
            "configblack",
            "mkdocs",
        },
        codeformatters={
            "python",
            "bash",
            "sh",
            "json",
            "toml",
            "yaml",
            "javascript",
            "js",
            "css",
            "html",
            "xml",
        },
)
```

versions:
mdformat==0.7.16
mdformat-admon==1.0.0

Thanks

**Comment by KyleKing** [comment]
Thanks for trying the plug-in!

I think the issue is that I need a minimum version constraint on 'mdit-py-plugins' to ">=0.3.2"

What version of Python are you using? Can you update that dependency?

I'm flying home now and I'll troubleshoot when I'm back on my laptop

**Comment by veghdev** [comment]
Thanks for developing the plug-in, it is very useful.

I'm using python 3.9, and generating dev dependencies with pip-compile:
mdit-py-plugins[linkify]==0.3.3
    # via
    #   jupytext
    #   mdformat-footnote
    #   mdformat-frontmatter
    #   mdformat-gfm
    #   mdformat-mkdocs

**Comment by KyleKing** [comment]
I was definitely overthinking it! You'll want to add `"admonition"` instead of `"admon"`. I could alias `admon` to support either, but I would prefer to have just one way

I've added a test here to make sure this use-case is supported:

https://github.com/KyleKing/mdformat-admon/blob/b3872f044651f3d9269b122d7a55abdbc396692b/tests/test_mdformat.py#L10-L16

Let me know if that works!

**Comment by veghdev** [comment]
@KyleKing Thanks a lot.
