### ISSUE TITLE
Latest `mdformat-admon` and `mdformat-gfm` conflicts

### ISSUE THREAD

**Issue by kdeldycke** [KyleKing/mdformat-admon#15]
Trying to install the last 2 versions of these plugins does not work because of a conflict on `mdit-py-plugins` requirements:

```shell-session
$ pip install --dry-run mdformat-gfm==0.3.5 mdformat-admon==1.0.2
Collecting mdformat-gfm==0.3.5
  Using cached mdformat_gfm-0.3.5-py3-none-any.whl (4.9 kB)
Collecting mdformat-admon==1.0.2
  Using cached mdformat_admon-1.0.2-py3-none-any.whl (4.7 kB)
Collecting markdown-it-py[linkify] (from mdformat-gfm==0.3.5)
  Using cached markdown_it_py-3.0.0-py3-none-any.whl (87 kB)
Collecting mdformat<0.8.0,>=0.7.5 (from mdformat-gfm==0.3.5)
  Using cached mdformat-0.7.16-py3-none-any.whl (29 kB)
Collecting mdformat-tables>=0.4.0 (from mdformat-gfm==0.3.5)
  Using cached mdformat_tables-0.4.1-py3-none-any.whl (4.6 kB)
Collecting mdit-py-plugins<0.4.0,>=0.2.0 (from mdformat-gfm==0.3.5)
  Using cached mdit_py_plugins-0.3.5-py3-none-any.whl (52 kB)
INFO: pip is looking at multiple versions of mdformat-admon to determine which version is compatible with other requirements. This could take a while.
ERROR: Cannot install mdformat-admon==1.0.2 and mdformat-gfm==0.3.5 because these package versions have conflicting dependencies.

The conflict is caused by:
    mdformat-gfm 0.3.5 depends on mdit-py-plugins<0.4.0 and >=0.2.0
    mdformat-admon 1.0.2 depends on mdit-py-plugins>=0.4.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```

Mirrors: https://github.com/hukkin/mdformat-gfm/issues/27

**Comment by KyleKing** [comment]
Thanks for catching this!

The newest version of `mdformat-admon` was to move code from distributed with the package to being distributed with `mdit-py-plugins`: https://github.com/KyleKing/mdformat-admon/pull/13/files#diff-13d7dfdeee64e87cc952bf329c9597f183f72b7e92363abcc17c0ed73f219fa6, so the latest version of `mdformat-admon` does depend on `mdit-py-plugins>=0.4.0`

I'll close this issue because there isn't anything I can do, but I'll +1 to your issue on `mdformat-gfm`

**Comment by kdeldycke** [comment]
Thanks @KyleKing for the detailed explanation. Indeed, looks like the fix should be on `mdformat-gfm` side.

**Comment by kdeldycke** [comment]
Just so you know, had the same conflict between `mdformat-deflist` and `mdformat-admon`:
- https://github.com/executablebooks/mdformat-deflist/issues/4
- https://github.com/executablebooks/mdformat-deflist/pull/5

**Comment by kdeldycke** [comment]
Again, `mdformat-myst` and `mdformat-admon` conflicts:
- https://github.com/executablebooks/mdformat-myst/issues/27
- https://github.com/executablebooks/mdformat-myst/pull/28

**Comment by KyleKing** [comment]
Thanks for catching the inconsistencies!

**Comment by KyleKing** [comment]
You inspired me to follow up on the packages I use as well:

https://github.com/KyleKing/mdformat-mkdocs/blob/112b9b174be6c642beae51539e1995b8cd37e745/pyproject.toml#L28-L38C6

Until `mdformat` 0.8 is released, there shouldn't be any issues with the versioning for these:

| No Issue | Package |
| -------- | ------- |
| ✅       | https://github.com/hukkin/mdformat-web/blob/8e69eceee166fc74cf99cfcd6ecad424289760d2/pyproject.toml#L38-L41 | 
| ✅       | https://github.com/hukkin/mdformat-beautysh/blob/f5bf08e30f453cba32ee6cb779e68afa12b19503/pyproject.toml#L31-L34 |
| ✅       | https://github.com/hukkin/mdformat-black/blob/5448af1e67d200f8861c8e04ec11726b6ec0e91c/pyproject.toml#L32-L35 |
| ✅       | https://github.com/hukkin/mdformat-config/blob/e53692b39eba9e4cbe3563753b0a5f0127392eac/pyproject.toml#L32-L36 |
| 🟨 - `mdformat<0.8` | https://github.com/executablebooks/mdformat-footnote/blob/80852fc20cfba7fd0330b9ac7a1a4df983542942/pyproject.toml#L22-L24 |
| 🟨 - `mdformat<0.8` | https://github.com/butler54/mdformat-frontmatter/blob/5dd12a22d4e91f10f0070374cb2e922c47a267a7/pyproject.toml#L20-L23 |
| 🟨 - `mdformat<0.8` | https://github.com/csala/mdformat-simple-breaks/blob/6a1ef11c4d0450826d5dd8a9da39712398016323/pyproject.toml#L19-L21 | 
| 🟨 - `mdformat<0.8` | https://github.com/executablebooks/mdformat-tables/blob/c169887bea9b3f4d16c6313eae8bea4b78c25f5a/pyproject.toml#L20 |
| 🟨 - `mdformat<0.8` | https://github.com/hukkin/mdformat-toc/blob/42624b6f3468da4f793ec7425da872b030714774/pyproject.toml#L32-L34 |
