### ISSUE TITLE
Support for `???` and `???+` doesn't look to be in 1.0.2?

### ISSUE THREAD

**Issue by jinnovation** [KyleKing/mdformat-admon#16]
First off, thanks for this project. Was just about to give up on `mdformat` for a project of mine until I found your plugin work here in executablebooks/mdformat#309.

Looking at the [release page for 1.0.2](https://github.com/KyleKing/mdformat-admon/releases/tag/v1.0.2), it mentions that 1.0.2 fixes #9.

However, looking at the commits to `main` since that tag, we see 282ca53c7869fddd9e056d08ab2315d59155b5f4, which corresponds to #13, i.e. precisely the PR that resolves #9.

So it sounds like the fix for #9 is in fact **not** in 1.0.2, and could use a follow-up release? 😅

**Comment by KyleKing** [comment]
The changes should be released! The only additional commit is an empty merge commit: https://github.com/KyleKing/mdformat-admon/compare/v1.0.2...main. Going to that commit directly appears as a diff from the GitHub UI, but it is really a non-change

Thanks for trying out the plugin and let me know if you have any other questions or issues!
