### ISSUE TITLE
Add installation instructions

### ISSUE THREAD

**Issue by lyz-code** [KyleKing/mdformat-admon#8]
Hi @KyleKing, first thank you **so much** for developing the plugin. Could you please add to the `README.md` the steps to install and make the plugin work?

Thanks

**Comment by KyleKing** [comment]
I updated the README and tested locally. I think everything should work for `!!!` based admonitions, and I'm starting on supporting the same style of syntax, but with different markers (#9)

Let me know if you run into any issue, or I could make any additional improvements!
